#pragma once
namespace studio {
struct ImageArchiveProfile {
    const char *path;
    const char *category;
};
inline constexpr ImageArchiveProfile image_archives[] = {
    {"romfs/a/2/4/4", "Healing portraits"}, {"romfs/a/0/2/6", "UI images"},
    {"romfs/a/0/2/7", "UI images"},         {"romfs/a/0/6/1", "Item icons"},
    {"romfs/a/0/6/2", "Pokemon icons"},     {"romfs/a/0/6/4", "UI images"},
    {"romfs/a/0/6/5", "UI images"},         {"romfs/a/0/6/6", "UI images"},
    {"romfs/a/0/6/7", "Battle UI"},         {"romfs/a/0/6/8", "Battle UI"},
    {"romfs/a/0/6/9", "UI images"},         {"romfs/a/0/7/0", "UI images"},
    {"romfs/a/0/7/1", "UI images"},         {"romfs/a/0/7/4", "UI images"},
    {"romfs/a/0/7/5", "UI images"},         {"romfs/a/0/7/6", "UI images"},
    {"romfs/a/0/7/9", "UI images"},         {"romfs/a/0/8/0", "UI images"},
    {"romfs/a/0/9/9", "UI images"},         {"romfs/a/1/0/0", "UI images"},
    {"romfs/a/1/0/2", "Field menu UI"},     {"romfs/a/1/0/4", "UI images"},
    {"romfs/a/1/0/9", "UI images"},         {"romfs/a/1/1/1", "UI images"},
    {"romfs/a/1/1/6", "UI images"},         {"romfs/a/1/1/7", "UI images"},
    {"romfs/a/1/2/3", "UI images"},         {"romfs/a/1/2/5", "Type and status icons"},
    {"romfs/a/1/2/8", "UI images"},         {"romfs/a/1/3/0", "UI images"},
    {"romfs/a/1/3/1", "UI images"},         {"romfs/a/1/3/2", "UI images"},
    {"romfs/a/1/3/3", "UI images"},         {"romfs/a/1/3/4", "UI images"},
    {"romfs/a/1/3/5", "UI images"},         {"romfs/a/1/3/6", "UI images"},
    {"romfs/a/1/3/7", "UI images"},         {"romfs/a/1/3/8", "Decoration images"},
    {"romfs/a/1/3/9", "UI images"},         {"romfs/a/1/4/2", "UI images"},
    {"romfs/a/1/4/7", "UI images"},         {"romfs/a/1/5/5", "Report UI"},
    {"romfs/a/1/5/7", "UI images"},         {"romfs/a/1/5/8", "Trainer icons"},
    {"romfs/a/1/6/0", "UI images"},         {"romfs/a/1/6/1", "UI images"},
    {"romfs/a/1/6/2", "UI images"},         {"romfs/a/1/6/3", "Map images"},
    {"romfs/a/1/6/4", "UI images"},         {"romfs/a/1/6/5", "UI images"},
    {"romfs/a/1/7/0", "UI images"},         {"romfs/a/1/7/1", "UI images"},
    {"romfs/a/1/7/2", "UI images"},         {"romfs/a/1/7/3", "Battle result labels"},
    {"romfs/a/2/2/6", "UI images"},         {"romfs/a/2/2/7", "UI images"},
    {"romfs/a/2/2/8", "Other images"},      {"romfs/a/2/3/0", "UI images"},
    {"romfs/a/2/3/2", "UI images"},         {"romfs/a/2/3/3", "UI images"},
    {"romfs/a/2/3/4", "UI images"},         {"romfs/a/2/3/5", "UI images"},
    {"romfs/a/2/3/8", "UI images"},         {"romfs/a/2/4/1", "UI images"},
    {"romfs/a/2/4/2", "UI images"},         {"romfs/a/2/4/3", "UI images"},
    {"romfs/a/2/4/6", "UI images"},         {"romfs/a/2/5/0", "Refresh UI"},
    {"romfs/a/2/5/1", "UI images"},         {"romfs/a/2/5/3", "UI images"},
    {"romfs/a/2/5/4", "UI images"},         {"romfs/a/2/5/9", "UI images"},
    {"romfs/a/2/6/0", "UI images"},         {"romfs/a/2/6/4", "Ribbon icons"},
    {"romfs/a/2/6/8", "UI images"},         {"romfs/a/2/7/0", "UI images"},
    {"romfs/a/2/7/3", "Pokedex artwork"},   {"romfs/a/2/7/4", "UI images"},
    {"romfs/a/2/8/0", "UI images"},         {"romfs/a/2/8/5", "UI images"},
    {"romfs/a/2/8/6", "UI images"},         {"romfs/a/2/8/7", "UI images"},
    {"romfs/a/2/8/8", "UI images"},         {"romfs/a/2/9/4", "Beans"},
    {"romfs/a/2/9/6", "UI images"},         {"romfs/a/2/9/7", "UI images"},
    {"romfs/a/2/9/8", "UI images"},         {"romfs/a/2/9/9", "UI images"},
    {"romfs/a/3/0/0", "UI images"},         {"romfs/a/3/0/1", "UI images"},
    {"romfs/a/3/0/2", "UI images"},         {"romfs/a/3/0/3", "UI images"},
    {"romfs/a/3/0/8", "UI images"},         {"romfs/a/3/0/9", "UI images"},
    {"romfs/a/3/1/0", "UI images"},         {"romfs/a/3/1/1", "UI images"},
    {"romfs/a/3/2/4", "UI images"},         {"romfs/a/3/2/8", "UI images"},
    {"romfs/a/3/2/9", "UI images"},         {"romfs/a/3/3/1", "UI images"},
};
}
