cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED DESTINATION)
  set(DESTINATION "${CMAKE_CURRENT_LIST_DIR}/../dependencies")
endif()
file(READ "${CMAKE_CURRENT_LIST_DIR}/dependencies.json" manifest)
string(JSON count LENGTH "${manifest}")
math(EXPR last "${count} - 1")
foreach(index RANGE ${last})
  foreach(key file url sha256 destination)
    string(JSON ${key} GET "${manifest}" ${index} ${key})
  endforeach()
  if(file STREQUAL "sdl3-vc.zip" AND NOT CMAKE_HOST_WIN32)
    continue()
  endif()
  if(EXISTS "${DESTINATION}/${destination}/.download-complete")
    continue()
  endif()
  file(MAKE_DIRECTORY "${DESTINATION}/downloads")
  set(archive "${DESTINATION}/downloads/${file}")
  message(STATUS "Downloading ${destination}")
  file(DOWNLOAD "${url}" "${archive}" EXPECTED_HASH "SHA256=${sha256}" TLS_VERIFY ON)
  set(unpack "${DESTINATION}/downloads/unpack")
  file(REMOVE_RECURSE "${unpack}")
  file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${unpack}")
  file(GLOB roots LIST_DIRECTORIES TRUE "${unpack}/*")
  list(LENGTH roots root_count)
  if(NOT root_count EQUAL 1)
    message(FATAL_ERROR "Unexpected archive layout for ${file}")
  endif()
  list(GET roots 0 root)
  file(MAKE_DIRECTORY "${DESTINATION}/${destination}")
  file(COPY "${root}/" DESTINATION "${DESTINATION}/${destination}")
  file(WRITE "${DESTINATION}/${destination}/.download-complete" "${sha256}")
  file(REMOVE_RECURSE "${unpack}")
  file(REMOVE "${archive}")
endforeach()
