set(STUDIO_GRAPHICS_SOURCE "" CACHE PATH "Prepared bgfx.cmake source tree")
set(STUDIO_GRAPHICS_BUILD "" CACHE PATH "Built bgfx.cmake tree")
set(STUDIO_IMGUI_SOURCE "" CACHE PATH "Dear ImGui docking source tree")
set(STUDIO_SDL_SOURCE "" CACHE PATH "Optional prepared SDL3 source tree")
if(STUDIO_SDL_SOURCE)
  set(SDL_TESTS OFF CACHE BOOL "" FORCE)
  set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
  set(SDL_SHARED OFF CACHE BOOL "" FORCE)
  set(SDL_STATIC ON CACHE BOOL "" FORCE)
  add_subdirectory("${STUDIO_SDL_SOURCE}" "${CMAKE_CURRENT_BINARY_DIR}/sdl3" EXCLUDE_FROM_ALL)
else()
  find_package(SDL3 3.4.16 REQUIRED CONFIG)
endif()
find_package(Threads REQUIRED)
foreach(dep bgfx bx bimg)
  find_library(STUDIO_${dep}_LIBRARY NAMES ${dep} PATHS "${STUDIO_GRAPHICS_BUILD}/cmake/${dep}" "${STUDIO_GRAPHICS_BUILD}/cmake/${dep}/Release" NO_DEFAULT_PATH REQUIRED)
endforeach()
set(STUDIO_PRECOMPILED_SHADERS "" CACHE PATH "Optional shaders compiled for this pinned bgfx revision")
if(NOT STUDIO_PRECOMPILED_SHADERS)
  find_program(STUDIO_SHADERC NAMES shaderc PATHS "${STUDIO_GRAPHICS_BUILD}/cmake/bgfx" "${STUDIO_GRAPHICS_BUILD}/cmake/bgfx/Release" NO_DEFAULT_PATH REQUIRED)
endif()
add_library(studio_imgui
  "${STUDIO_IMGUI_SOURCE}/imgui.cpp" "${STUDIO_IMGUI_SOURCE}/imgui_draw.cpp"
  "${STUDIO_IMGUI_SOURCE}/imgui_tables.cpp" "${STUDIO_IMGUI_SOURCE}/imgui_widgets.cpp"
  "${STUDIO_IMGUI_SOURCE}/backends/imgui_impl_sdl3.cpp")
target_include_directories(studio_imgui PUBLIC "${STUDIO_IMGUI_SOURCE}")
target_link_libraries(studio_imgui PUBLIC SDL3::SDL3)
add_library(studio_viewport STATIC src/native/map_authoring_objects.cpp src/native/existing_map_editor.cpp src/native/character_registration_editor.cpp src/native/zone_editor.cpp src/native/pedestrian_editor.cpp src/native/ambient_sound_preview.cpp src/native/field_system_inspector.cpp src/native/warp_ride_workspace.cpp src/native/tutorial_controller.cpp src/native/map_cursor.cpp src/native/encounter_editor.cpp src/native/overworld_editor.cpp src/native/overworld_shape_gizmo.cpp src/native/pickup_editor.cpp src/native/weather_editor.cpp src/native/warp_editor.cpp src/native/project_binding.cpp src/native/project_workspace.cpp src/native/camera_editor.cpp src/native/collision_editor.cpp src/native/collision_viewport.cpp src/native/map_authoring_ground.cpp src/native/map_authoring_workspace.cpp src/native/map_authoring_viewport.cpp src/native/refresh_inspector.cpp src/native/refresh_overlay.cpp src/native/material_editor.cpp src/native/uv_editor.cpp src/native/uv_motion_editor.cpp src/native/texture_painter.cpp src/native/lighting_table_editor.cpp src/native/model_workspace.cpp src/native/battle_effect_browser.cpp src/native/clothing_workspace.cpp src/native/pokemon_settings_editor.cpp src/native/placement_editor.cpp src/native/application.cpp src/native/renderer.cpp src/native/imgui_renderer.cpp src/native/preferences.cpp src/native/folder_picker.cpp src/native/material_inspector.cpp src/native/scene_browser.cpp src/native/map_selector.cpp src/native/post_process.cpp src/native/particle_renderer.cpp src/native/spatial_overlay.cpp src/native/material_motion_editor.cpp src/native/cry_editor.cpp src/native/audio_editor.cpp src/native/map_music.cpp src/native/refresh_feeding_preview.cpp src/native/geometry_editor.cpp src/native/image_editor.cpp src/native/bone_gizmo.cpp src/native/skeletal_motion_editor.cpp src/native/skeleton_editor.cpp src/native/model_exchange_editor.cpp src/native/pokemon_bundle_editor.cpp src/native/visibility_motion_editor.cpp src/native/interaction_inspector.cpp src/native/conversation_editor.cpp src/native/conversation_scene_tools.cpp src/native/script_sound_picker.cpp)
target_include_directories(studio_viewport PUBLIC "${STUDIO_GRAPHICS_SOURCE}/bgfx/include" "${STUDIO_GRAPHICS_SOURCE}/bx/include" "${STUDIO_GRAPHICS_SOURCE}/bgfx/examples/common")
target_compile_definitions(studio_viewport PUBLIC BX_CONFIG_DEBUG=0 SDL_MAIN_HANDLED)
target_link_libraries(studio_viewport PUBLIC studio_tutorials studio_map_authoring studio_scene studio_imgui "${STUDIO_bgfx_LIBRARY}" "${STUDIO_bimg_LIBRARY}" "${STUDIO_bx_LIBRARY}" Threads::Threads ${CMAKE_DL_LIBS})
if(MSVC)
  target_compile_options(studio_viewport PUBLIC /Zc:__cplusplus /Zc:preprocessor)
  target_compile_definitions(studio_viewport PUBLIC NOMINMAX WIN32_LEAN_AND_MEAN)
endif()
if(WIN32)
  target_link_libraries(studio_viewport PUBLIC psapi)
else()
  find_package(X11 REQUIRED)
  find_package(OpenGL REQUIRED)
  target_link_libraries(studio_viewport PUBLIC X11::X11 OpenGL::GL)
endif()
add_executable(usum-viewport src/native/main.cpp)
target_link_libraries(usum-viewport PRIVATE studio_viewport)
set(studio_viewport_programs usum-viewport)

set(shader_outputs)
foreach(profile glsl spirv)
  if(profile STREQUAL "glsl")
    set(shader_profile 330)
  else()
    set(shader_profile spirv)
  endif()
  foreach(effect environment post particle spatial)
  foreach(stage vs fs)
    if(stage STREQUAL "vs")
      set(shader_type vertex)
    else()
      set(shader_type fragment)
    endif()
    set(source "${CMAKE_CURRENT_SOURCE_DIR}/src/native/shaders/${stage}_${effect}.sc")
    set(output "${CMAKE_CURRENT_BINARY_DIR}/viewport-shaders/${profile}/${stage}_${effect}.bin")
    if(STUDIO_PRECOMPILED_SHADERS)
      add_custom_command(OUTPUT "${output}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/viewport-shaders/${profile}"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${STUDIO_PRECOMPILED_SHADERS}/${profile}/${stage}_${effect}.bin" "${output}"
        DEPENDS "${STUDIO_PRECOMPILED_SHADERS}/${profile}/${stage}_${effect}.bin" VERBATIM)
    else()
    add_custom_command(OUTPUT "${output}"
      COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/viewport-shaders/${profile}"
      COMMAND "${STUDIO_SHADERC}" -f "${source}" -o "${output}" --type ${shader_type} --platform linux -p ${shader_profile} -i "${STUDIO_GRAPHICS_SOURCE}/bgfx/src" --varyingdef "${CMAKE_CURRENT_SOURCE_DIR}/src/native/shaders/varying.def.sc"
      DEPENDS "${source}" src/native/shaders/varying.def.sc "${STUDIO_GRAPHICS_SOURCE}/bgfx/src/bgfx_shader.sh" "${STUDIO_SHADERC}" VERBATIM)
    endif()
    list(APPEND shader_outputs "${output}")
  endforeach()
  endforeach()
endforeach()
add_custom_target(studio_viewport_shaders DEPENDS ${shader_outputs})
foreach(program IN LISTS studio_viewport_programs)
  add_dependencies(${program} studio_viewport_shaders)
  set_property(TARGET ${program} APPEND PROPERTY LINK_DEPENDS "${shader_outputs}")

  add_custom_command(TARGET ${program} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${CMAKE_CURRENT_BINARY_DIR}/viewport-shaders" "$<TARGET_FILE_DIR:${program}>/viewport-shaders"
    VERBATIM)
  if(WIN32)
    get_target_property(studio_sdl_type SDL3::SDL3 TYPE)
    if(studio_sdl_type STREQUAL "SHARED_LIBRARY")
      add_custom_command(TARGET ${program} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "$<TARGET_FILE:SDL3::SDL3>" "$<TARGET_FILE_DIR:${program}>" VERBATIM)
    endif()
  endif()

  add_custom_command(TARGET ${program} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${CMAKE_CURRENT_SOURCE_DIR}/resources" "$<TARGET_FILE_DIR:${program}>/resources" VERBATIM)
  set_property(TARGET ${program} APPEND PROPERTY LINK_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/resources/fonts/DejaVuSans.ttf")

endforeach()

if(WIN32)
  enable_language(RC)
  set(STUDIO_APP_ICON "${CMAKE_CURRENT_SOURCE_DIR}/icon/icon.ico")
  configure_file(src/native/application.rc.in "${CMAKE_CURRENT_BINARY_DIR}/application.rc" @ONLY)
  target_sources(usum-viewport PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/application.rc")
  set_source_files_properties("${CMAKE_CURRENT_BINARY_DIR}/application.rc" PROPERTIES OBJECT_DEPENDS "${STUDIO_APP_ICON}")
endif()
add_custom_command(TARGET usum-viewport POST_BUILD
  COMMAND ${CMAKE_COMMAND} -E copy_if_different "${CMAKE_CURRENT_SOURCE_DIR}/icon/icon.png" "$<TARGET_FILE_DIR:usum-viewport>/resources/icon.png" VERBATIM)
set_property(TARGET usum-viewport APPEND PROPERTY LINK_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/icon/icon.png")

